/**
 * Row shapes for every table the client touches.
 *
 * Hand-written rather than generated by `supabase gen types` because the
 * CLI isn't authenticated here. Regenerating later is the right move —
 * these are deliberately named to match, so the swap is mechanical.
 *
 * The enums must stay in step with supabase/migrations/…_core_schema.sql.
 * DOMAIN_ORDER below is also the plan's presentation order.
 */

export const DOMAINS = ["motor", "communication", "cognitive", "social_emotional"] as const;
export type Domain = (typeof DOMAINS)[number];

// The original 7 activity/milestone bands, still used by milestones and
// vaccination-adjacent content. See ACTIVITY_LIBRARY_AGE_BANDS below for the
// 28 finer bands activities themselves use as of content/activity_library.csv
// — both sets are valid age_band values in the DB (widening only adds
// labels, see supabase/migrations/20260808100000_widen_activity_bands.sql),
// so AgeBand covers both rather than picking one.
export const AGE_BANDS = [
  "m0_3",
  "m4_6",
  "m7_12",
  "m13_24",
  "m25_36",
  "y3_5",
  "y5_7",
] as const;

/**
 * The 28 three-month bands activities are seeded at
 * (content/activity_library.csv), from
 * supabase/migrations/20260808100000_widen_activity_bands.sql. m0_3 and
 * m4_6 are shared with AGE_BANDS above (identically sized), not duplicated.
 */
export const ACTIVITY_LIBRARY_AGE_BANDS = [
  "m0_3",
  "m4_6",
  "m7_9",
  "m10_12",
  "m13_15",
  "m16_18",
  "m19_21",
  "m22_24",
  "m25_27",
  "m28_30",
  "m31_33",
  "m34_36",
  "y3_0",
  "y3_3",
  "y3_6",
  "y3_9",
  "y4_0",
  "y4_3",
  "y4_6",
  "y4_9",
  "y5_0",
  "y5_3",
  "y5_6",
  "y5_9",
  "y6_0",
  "y6_3",
  "y6_6",
  "y6_9",
] as const;

export type AgeBand = (typeof AGE_BANDS)[number] | (typeof ACTIVITY_LIBRARY_AGE_BANDS)[number];

/** Labels for display. The DB stores the enum; the UI never shows it raw. */
export const DOMAIN_LABEL: Record<Domain, string> = {
  motor: "Motor",
  communication: "Communication",
  cognitive: "Cognitive",
  social_emotional: "Social & Emotional",
};

export const AGE_BAND_LABEL: Record<AgeBand, string> = {
  m0_3: "0–3 months",
  m4_6: "4–6 months",
  m7_12: "7–12 months",
  m13_24: "13–24 months",
  m25_36: "25–36 months",
  y3_5: "3–5 years",
  y5_7: "5–7 years",
  m7_9: "7–9 months",
  m10_12: "10–12 months",
  m13_15: "13–15 months",
  m16_18: "16–18 months",
  m19_21: "19–21 months",
  m22_24: "22–24 months",
  m25_27: "25–27 months",
  m28_30: "28–30 months",
  m31_33: "31–33 months",
  m34_36: "34–36 months",
  y3_0: "3y–3y3m",
  y3_3: "3y3m–3y6m",
  y3_6: "3y6m–3y9m",
  y3_9: "3y9m–4y",
  y4_0: "4y–4y3m",
  y4_3: "4y3m–4y6m",
  y4_6: "4y6m–4y9m",
  y4_9: "4y9m–5y",
  y5_0: "5y–5y3m",
  y5_3: "5y3m–5y6m",
  y5_6: "5y6m–5y9m",
  y5_9: "5y9m–6y",
  y6_0: "6y–6y3m",
  y6_3: "6y3m–6y6m",
  y6_6: "6y6m–6y9m",
  y6_9: "6y9m–7y",
};

// --- Global content ---------------------------------------------------

export type Activity = {
  id: string;
  domain: Domain;
  age_band: AgeBand;
  title: string;
  /** One sentence: what the activity is. Shown in the collapsed preview. */
  why: string;
  /** A representative number derived from duration_label's range; null for "Ongoing". */
  duration_minutes: number | null;
  /** The source range as text, e.g. "5–10 min" or "Ongoing" — prefer this for display. */
  duration_label: string | null;
  materials: string;
  /** Step-by-step how-to, newline-separated. Distinct from `why`. */
  instructions: string | null;
  /** One sentence: the developmental reason this activity is worth doing.
   *  Null when the source content had nothing genuine to split out — the
   *  UI falls back to a per-domain line rather than showing a gap. */
  benefit: string | null;
};

export type Milestone = {
  id: string;
  domain: Domain;
  age_band: AgeBand;
  stage_label: string;
  description: string;
  typical_age_min_months: number;
  typical_age_max_months: number;
  guide: { try?: string; watch?: string; see?: string } | null;
};

/**
 * How a vaccine is positioned for a parent.
 *
 *   essential   — India's Universal Immunisation Programme. Free at
 *                 government facilities; the baseline every child gets.
 *   recommended — IAP advises it beyond the UIP, for broader protection.
 *   situational — only for specific geography, risk or medical need, and
 *                 never presented as something a typical child is missing.
 */
export const VACCINE_TIERS = ["essential", "recommended", "situational"] as const;
export type VaccineTier = (typeof VACCINE_TIERS)[number];

export const VACCINE_TIER_LABEL: Record<VaccineTier, string> = {
  essential: "Essential",
  recommended: "Recommended",
  situational: "Situational",
};

export const VACCINE_TIER_BLURB: Record<VaccineTier, string> = {
  essential: "Part of India's Universal Immunisation Programme.",
  recommended: "Advised by the Indian Academy of Pediatrics for broader protection.",
  situational: "Only needed for specific risks, places or medical conditions. Ask your doctor.",
};

/**
 * The one clause per tier worth emphasising, split out of the blurb so the
 * UI can weight it. Cost is the thing a family most needs to know and most
 * often assumes wrongly — that the UIP schedule is free at government
 * centres shouldn't be buried mid-sentence in muted grey.
 */
export const VACCINE_TIER_HIGHLIGHT: Record<VaccineTier, string | null> = {
  essential: "Free at government centres.",
  recommended: null,
  situational: null,
};

export type VaccinationScheduleItem = {
  id: string;
  vaccine_name: string;
  tier: VaccineTier;
  /** Display string — real schedules are ranges ("16–24 months"). */
  age_label: string;
  /** Exact age in days; the sort key. */
  age_days: number;
  recommended_age_months: number;
  dose_label: string | null;
  notes: string | null;
  /** "NIS" (government) or "IAP" — every row is traceable. */
  source: string | null;
};

// --- Family data ------------------------------------------------------

export type Profile = {
  id: string;
  parent_name: string | null;
  /** mother | father | prefer_not_to_say — see lib/parentCare.ts ParentRole. */
  relationship: string | null;
  /** vaginal | caesarean | prefer_not_to_say — see lib/parentCare.ts DeliveryType. */
  birth_method: string | null;
  /** exclusive | combination | formula | prefer_not_to_say — see lib/parentCare.ts FeedingMethod. */
  feeding_method: string | null;
  /** omnivore | vegetarian | vegan — see lib/parentCare.ts DietaryPreference. */
  diet: string | null;
  /** Lowercased allergen names. */
  allergies: string[];
  phone: string | null;
  /** IANA zone. Every "today" in the product derives from this. */
  timezone: string;
  created_at: string;
};

export type Child = {
  id: string;
  parent_id: string;
  name: string;
  date_of_birth: string; // YYYY-MM-DD
  gender: string | null;
  /**
   * Weeks of gestation at birth: 40 = full term, lower = preterm, null =
   * never asked. Drives corrected age on the developmental surfaces only
   * — see lib/childAge.ts. Vaccination schedules deliberately stay on
   * chronological age, which is what they're actually written against.
   */
  gestational_weeks: number | null;
  /** The child's own allergens, lowercased. NOT the parent's — that's
   *  Profile.allergies, a separate fact used for the parent's meals. */
  allergies: string[];
  created_at: string;
};

export type DailyPlanRow = {
  id: string;
  child_id: string;
  plan_date: string; // family-local date
  motor_activity_id: string | null;
  communication_activity_id: string | null;
  cognitive_activity_id: string | null;
  social_emotional_activity_id: string | null;
  swaps: Partial<Record<Domain, number>>;
  generated_at: string;
};

/** A plan with its activities resolved — what screens actually render. */
export type DailyPlan = {
  id: string;
  planDate: string;
  /** Always four, in DOMAIN order, nulls dropped. */
  activities: Activity[];
  swaps: Partial<Record<Domain, number>>;
};

/**
 * One row per activity per day. Created on Start, updated on Complete.
 *
 *   started_at set, completed_at null  -> in progress, or abandoned
 *   both set                           -> done
 *   started_at null, completed_at set  -> marked done without starting
 *
 * Only rows with `completed_at` count as done. Anything reading progress
 * must filter on that, not on the row existing.
 */
export type ActivityLogEntry = {
  id: string;
  child_id: string;
  activity_id: string | null;
  /** Snapshotted at write time — never re-read from `activities`. */
  domain: Domain;
  title: string;
  age_band: AgeBand;
  plan_date: string | null;
  started_at: string | null;
  completed_at: string | null;
  note: string | null;
  photo_path: string | null;
};

export type ChildMilestone = {
  id: string;
  child_id: string;
  milestone_id: string;
  achieved_at: string;
  note: string | null;
};

/**
 * given  — administered_on is set, the dose actually happened.
 * unsure — a parent flagged the dose as unsure whether it happened, with
 *          an optional note; administered_on is null.
 */
export const VACCINATION_STATUSES = ["given", "unsure"] as const;
export type VaccinationStatus = (typeof VACCINATION_STATUSES)[number];

export type ChildVaccination = {
  id: string;
  child_id: string;
  vaccination_id: string;
  status: VaccinationStatus;
  /** Set only when status is "given". */
  administered_on: string | null;
  notes: string | null;
};

// --- Mother postpartum recovery ---------------------------------------

/**
 * The mother's own daily recovery set — distinct from the static
 * "Postpartum Care" library (lib/parentCare.ts CARE_TOPICS), which stays
 * as read-only reference reading. This is the actionable, rotating daily
 * activities, mirroring the child's activities/daily_plans model but
 * scoped to month_postpartum (1–12) and the mother's birth method instead
 * of age_band and domain.
 */
export const MOTHER_ACTIVITY_CATEGORIES = [
  "physical_recovery",
  "emotional_wellness",
  "mother_baby_bonding",
  "couple_connection",
] as const;
export type MotherActivityCategory = (typeof MOTHER_ACTIVITY_CATEGORIES)[number];

export const MOTHER_ACTIVITY_CATEGORY_LABEL: Record<MotherActivityCategory, string> = {
  physical_recovery: "Physical recovery",
  emotional_wellness: "Emotional wellness",
  mother_baby_bonding: "Bonding with baby",
  couple_connection: "Couple connection",
};

/** "all" = every mother regardless of birth method. */
export type MotherActivityRelevance = "all" | "vaginal" | "caesarean";
export type MotherActivityTimeOfDay = "anytime" | "morning" | "evening" | "during_nap";
export type MotherActivityEffort = "gentle" | "moderate";
export type MotherActivityWithBaby = "yes" | "no" | "optional";

export type MotherActivity = {
  id: string;
  category: MotherActivityCategory;
  month_postpartum: number;
  applies_to: MotherActivityRelevance;
  title: string;
  description: string;
  duration_minutes: number;
  time_of_day: MotherActivityTimeOfDay;
  with_baby: MotherActivityWithBaby;
  effort_level: MotherActivityEffort;
  /** What changes about this activity in later months, when given. */
  progression_notes: string | null;
};

export type MotherDailyPlanRow = {
  id: string;
  profile_id: string;
  plan_date: string; // family-local date
  physical_recovery_activity_id: string | null;
  emotional_wellness_activity_id: string | null;
  mother_baby_bonding_activity_id: string | null;
  couple_connection_activity_id: string | null;
  swaps: Partial<Record<MotherActivityCategory, number>>;
};

/** A mother plan with its activities resolved — what screens actually render. */
export type MotherDailyPlan = {
  id: string;
  planDate: string;
  /** Always four, in MOTHER_ACTIVITY_CATEGORIES order, nulls dropped. */
  activities: MotherActivity[];
  swaps: Partial<Record<MotherActivityCategory, number>>;
};

export type CopilotConversation = {
  id: string;
  child_id: string;
  title: string | null;
  created_at: string;
  last_message_at: string;
};

export type CopilotMessage = {
  id: string;
  conversation_id: string;
  role: "parent" | "copilot";
  content: string;
  created_at: string;
};
