-- Strips the generic "closer" sentence (one of a small recycled
-- pool of parenting-tip lines with no connection to the specific
-- activity) from the tail of `benefit`, leaving the genuine
-- domain/age-specific developmental claim — matching the field's own
-- documented shape ("One sentence: the developmental reason...").
-- Regenerated from content/activity_library.csv; batch 3/4.
update activities as a
set benefit = v.new_benefit
from (values
  ('coins-y3_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('living-things-need-y3_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('simple-map-reading-y3_6', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('manage-waiting-y3_6', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('what-you-need-y3_6', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('others-feelings-first-y3_6', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('resilience-story-y3_6', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('disagree-respectfully-y3_6', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('gratitude-letter-y3_6', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('cooking-science-y3_6', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('blindfold-smell-test-y3_6', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('shadow-puppets-y3_6', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('rhythm-pattern-y3_6', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('plant-observation-journal-y3_6', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('own-school-bag-y3_6', 'Children this age are far more capable than they are usually allowed to be, and real responsibility builds real confidence.'),
  ('manage-belongings-y3_6', 'Children this age are far more capable than they are usually allowed to be, and real responsibility builds real confidence.'),
  ('skip-relay-race-y3_9', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('stand-tiptoes-y3_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('throw-overhand-i-y3_9', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('balance-wobble-board-y3_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('walk-hands-y3_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('stair-running-y3_9', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('dribble-around-obstacles-y3_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('landing-from-jump-y3_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('letter-formation-y3_9', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('sewing-running-stitch-y3_9', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('origami-y3_9', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('tying-knot-y3_9', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('scene-from-imagination-y3_9', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('model-from-plan-y3_9', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('read-short-book-y3_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('write-short-sentence-y3_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('explain-thinking-y3_9', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('presentation-family-y3_9', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('interview-family-member-y3_9', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('understand-idioms-y3_9', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('create-own-book-y3_9', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('debate-evidence-y3_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('addition-subtraction-20-y3_9', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('halves-quarters-y3_9', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('weight-comparison-y3_9', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('concept-time-duration-y3_9', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('animal-classification-y3_9', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('create-survey-y3_9', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('handle-unfairness-y3_9', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('include-outsider-y3_9', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('persistence-practice-y3_9', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('manage-boredom-y3_9', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('recognise-own-triggers-y3_9', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('celebrate-failure-y3_9', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('garden-science-y3_9', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('colour-mixing-y3_9', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('build-marble-run-y3_9', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('listen-classical-music-y3_9', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('clay-pottery-y3_9', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('responsible-pet-care-y3_9', 'Doing things for themselves builds the planning and sequencing skills that also support learning.'),
  ('money-small-purchase-y3_9', 'Children this age are far more capable than they are usually allowed to be, and real responsibility builds real confidence.'),
  ('metres-without-stopping-y4_0', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('ride-bicycle-y4_0', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('non-dominant-foot-i-y4_0', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('throw-distance-y4_0', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('from-50-cm-y4_0', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('move-music-y4_0', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('aim-kick-y4_0', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('side-shuffle-race-y4_0', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('letter-formation-i-y4_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('draw-portrait-person-y4_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('knit-or-crochet-y4_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('cut-complex-shape-y4_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('freestanding-tall-tower-y4_0', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('construct-paper-aeroplane-y4_0', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('level-1-early-reader-y4_0', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('write-own-story-y4_0', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('20-sight-words-y4_0', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('simile-introduction-y4_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('story-different-ending-y4_0', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('listen-draw-y4_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('read-simple-poem-y4_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('write-letter-y4_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('addition-carrying-y4_0', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('number-line-y4_0', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('measure-non-standard-units-y4_0', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('plant-life-cycle-y4_0', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('force-motion-y4_0', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('3d-shape-names-y4_0', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('you-need-help-y4_0', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('handle-being-wrong-y4_0', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('interest-another-s-world-y4_0', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('disagree-politely-adult-y4_0', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('group-project-contribution-y4_0', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('care-something-living-y4_0', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('leaf-printing-y4_0', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('make-instruments-y4_0', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('room-torch-exploration-y4_0', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('make-kite-y4_0', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('cooking-y4_0', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('manage-pocket-money-y4_0', 'Doing things for themselves builds the planning and sequencing skills that also support learning.'),
  ('first-aid-basics-y4_0', 'Children this age are far more capable than they are usually allowed to be, and real responsibility builds real confidence.'),
  ('without-training-wheels-y4_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('skip-rope-y4_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('throw-catch-ii-y4_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('kick-penalty-goal-y4_3', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('backwards-skip-y4_3', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('cartwheels-y4_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('swim-basic-stroke-y4_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('sprint-30-metres-y4_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('letter-formation-ii-y4_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('sewing-simple-shape-y4_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('tie-bow-y4_3', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('or-tile-pattern-y4_3', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('soap-or-clay-y4_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('design-then-build-y4_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('read-level-2-reader-y4_3', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('write-recount-y4_3', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('punctuation-awareness-y4_3', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('parts-story-y4_3', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('read-aloud-expression-y4_3', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('persuasive-letter-y4_3', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('create-crossword-family-y4_3', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('newspaper-report-y4_3', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('multiplication-introduction-y4_3', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('division-introduction-y4_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('fractions-y4_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('weather-patterns-y4_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('simple-electrical-circuit-y4_3', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('clock-reading-y4_3', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('mentor-younger-child-y4_3', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('peer-conflict-independently-y4_3', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('understand-different-opinions-y4_3', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('family-decision-together-y4_3', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('identify-own-strengths-y4_3', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('or-help-community-y4_3', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('marble-run-engineering-y4_3', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('dissect-flower-y4_3', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('make-test-boats-y4_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('stargazing-moon-journal-y4_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('make-natural-dyes-y4_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('full-simple-meal-y4_3', 'This develops the independence that starting school will require.'),
  ('manage-own-health-y4_3', 'Doing things for themselves builds the planning and sequencing skills that also support learning.'),
  ('sprint-baton-pass-y4_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('hop-scotch-y4_6', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('swim-10-metres-y4_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('throw-catch-i-y4_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('gymnastics-y4_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('balance-skateboard-board-y4_6', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('dribble-basketball-y4_6', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('long-jump-y4_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('letter-formation-iii-y4_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('perspective-drawing-y4_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('cross-stitch-y4_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('build-circuit-y4_6', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('carve-vegetable-print-y4_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('design-logo-y4_6', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('chapter-book-ii-y4_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('write-poem-y4_6', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('aloud-younger-child-y4_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('word-problem-maths-y4_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('speech-favourite-topic-y4_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('alliteration-assonance-y4_6', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('research-topic-y4_6', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('write-instructions-y4_6', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('times-tables-y4_6', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('understand-place-value-y4_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('graph-reading-y4_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('life-cycles-y4_6', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('simple-machines-y4_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('map-making-y4_6', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('self-manage-task-completion-y4_6', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('peer-teaching-y4_6', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('navigate-clique-dynamics-y4_6', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('goal-setting-y4_6', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('emotions-real-time-y4_6', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('cultural-curiosity-y4_6', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('build-terrarium-y4_6', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('colour-mixing-science-y4_6', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('knot-tying-y4_6', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('rhythm-composition-y4_6', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('taste-describe-y4_6', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('personal-safety-rules-y4_6', 'Children this age are far more capable than they are usually allowed to be, and real responsibility builds real confidence.'),
  ('budget-outing-y4_6', 'Doing things for themselves builds the planning and sequencing skills that also support learning.'),
  ('sprint-circuit-y4_9', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('simple-rules-y4_9', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('bicycle-rough-terrain-y4_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('swim-25-metres-y4_9', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('gymnastics-floor-sequence-y4_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('dance-sequence-y4_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('throw-catch-moving-y4_9', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('dribble-around-markers-y4_9', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('alphabet-capitals-lowercase-y4_9', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('comic-strip-creation-y4_9', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('puppet-making-y4_9', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('calligraphy-y4_9', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('build-mechanical-toy-y4_9', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('jigsaw-puzzle-y4_9', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('read-chapter-book-y4_9', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('write-non-fiction-report-y4_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('argue-both-sides-y4_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('reading-comprehension-questions-y4_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('vocabulary-context-clues-y4_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('research-present-y4_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('write-dialogue-y4_9', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('simple-newspaper-article-y4_9', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('times-tables-i-y4_9', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('fractions-number-line-y4_9', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('perimeter-y4_9', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('food-chains-y4_9', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('states-matter-y4_9', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('compass-directions-y4_9', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('set-own-goals-y4_9', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('adult-help-appropriately-y4_9', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('digital-citizenship-y4_9', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('own-health-appointment-y4_9', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('others-without-envy-y4_9', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('read-facial-expressions-y4_9', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('dissection-y4_9', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('build-bridge-i-y4_9', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('night-sky-observation-y4_9', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('paper-marbling-y4_9', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('sound-wave-experiment-y4_9', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('personal-hygiene-independence-y4_9', 'Doing things for themselves builds the planning and sequencing skills that also support learning.'),
  ('laundry-contribution-y4_9', 'Doing things for themselves builds the planning and sequencing skills that also support learning.'),
  ('team-sport-strategy-y5_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('swim-breathing-technique-y5_0', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('cycling-route-planning-y5_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('gymnastics-sequence-y5_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('jump-rope-i-y5_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('rock-climbing-y5_0', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('sprint-technique-i-y5_0', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('relay-race-strategy-y5_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('write-story-i-y5_0', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('technical-drawing-y5_0', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('build-electronic-kit-y5_0', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('engraving-y5_0', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('detailed-nature-drawing-y5_0', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('architectural-model-y5_0', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('chapter-book-i-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('write-argument-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('understand-subtext-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('reported-speech-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('prefix-suffix-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('research-project-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('write-newspaper-y5_0', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('grammar-clauses-phrases-y5_0', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('times-tables-ii-y5_0', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('long-multiplication-y5_0', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('bar-graph-creation-y5_0', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('earth-solar-system-y5_0', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('angles-introduction-y5_0', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('biography-reading-discussion-y5_0', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('manage-multiple-responsibilities-y5_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('conflict-without-adult-y5_0', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('another-s-perspective-fully-y5_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('resilience-from-failure-y5_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('manage-screen-time-y5_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('understand-misinformation-basics-y5_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('astronomy-observation-journal-y5_0', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('build-compost-bin-y5_0', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('photography-project-y5_0', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('fermentation-observation-y5_0', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('architecture-observation-walk-y5_0', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('plan-cook-meal-y5_0', 'Children who genuinely contribute at home tend to be more capable and more confident.'),
  ('navigate-independently-y5_0', 'Children who genuinely contribute at home tend to be more capable and more confident.'),
  ('orienteering-y5_3', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('batting-y5_3', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('swim-backstroke-10m-y5_3', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('handstand-y5_3', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('sprint-start-y5_3', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('hill-climb-y5_3', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('ball-control-y5_3', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('variant-freeze-tag-y5_3', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('write-story-y5_3', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('make-zine-y5_3', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('scale-drawing-y5_3', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('complex-origami-y5_3', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('build-simple-catapult-y5_3', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('batik-y5_3', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('read-novel-y5_3', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-book-report-y5_3', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('vocabulary-word-roots-y5_3', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('debate-i-y5_3', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('write-script-y5_3', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('analyse-poem-y5_3', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('edit-own-writing-y5_3', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('persuasive-speech-y5_3', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('times-tables-iii-y5_3', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('long-division-y5_3', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('decimals-introduction-y5_3', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('classify-rocks-y5_3', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('history-timeline-project-y5_3', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('logic-puzzles-y5_3', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('manage-time-project-y5_3', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('give-constructive-feedback-y5_3', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('handle-criticism-gracefully-y5_3', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('advocate-someone-else-y5_3', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('peer-mediation-y5_3', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('discuss-moral-dilemma-y5_3', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('tie-dye-y5_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('candle-making-y5_3', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('build-periscope-y5_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('kiln-pit-fire-y5_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.')
) as v(id, new_benefit)
where a.id = v.id;
