-- Strips the generic "closer" sentence (one of a small recycled
-- pool of parenting-tip lines with no connection to the specific
-- activity) from the tail of `benefit`, leaving the genuine
-- domain/age-specific developmental claim — matching the field's own
-- documented shape ("One sentence: the developmental reason...").
-- Regenerated from content/activity_library.csv; batch 4/4.
update activities as a
set benefit = v.new_benefit
from (values
  ('acoustic-science-y5_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('own-study-schedule-y5_3', 'Children who genuinely contribute at home tend to be more capable and more confident.'),
  ('solo-public-transaction-y5_3', 'This develops the organisation and self-management that school increasingly demands.'),
  ('badminton-y5_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('handstand-walk-y5_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('swim-50-metres-y5_6', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('bicycle-long-distance-y5_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('cricket-bowling-y5_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('gymnastics-beam-y5_6', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('archery-i-y5_6', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('frisbee-accurate-throw-y5_6', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('short-story-collection-y5_6', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('macrame-y5_6', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('perspective-drawing-i-y5_6', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('build-hydraulic-arm-y5_6', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('scratch-coding-y5_6', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('print-making-y5_6', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('read-novel-series-y5_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('from-another-perspective-y5_6', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('homophone-homonym-work-y5_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('interview-transcribe-y5_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('read-review-film-y5_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('word-etymology-project-y5_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-acrostic-poem-y5_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('comprehension-inference-y5_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('percentages-y5_6', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('negative-numbers-y5_6', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('area-rectangle-y5_6', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('electricity-magnetism-y5_6', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('human-body-systems-y5_6', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('probability-y5_6', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('recognise-unhealthy-relationships-y5_6', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('practice-saying-no-y5_6', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('manage-academic-pressure-y5_6', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('digital-empathy-y5_6', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('gratitude-journal-y5_6', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('cultural-exchange-meal-y5_6', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('optical-illusion-art-y5_6', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('fossil-making-y5_6', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('make-weather-station-y5_6', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('sound-science-y5_6', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('or-chicken-wing-y5_6', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('plan-fundraiser-y5_6', 'Independence and responsibility at this age build competence that carries well beyond the specific task.'),
  ('travel-independently-y5_6', 'Independence and responsibility at this age build competence that carries well beyond the specific task.'),
  ('football-y5_9', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('swimming-race-y5_9', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('bicycle-navigation-y5_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('rock-climbing-i-y5_9', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('trampoline-y5_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('tennis-y5_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('sprint-technique-y5_9', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('cricket-batting-y5_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('write-personal-essay-y5_9', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('woodworking-y5_9', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('animated-flip-book-y5_9', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('simple-cushion-cover-y5_9', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('programme-simple-app-y5_9', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('plaster-into-mould-y5_9', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('read-classic-novel-y5_9', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('write-biography-y5_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('pr-cis-writing-y5_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('active-passive-voice-y5_9', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('read-poetry-aloud-y5_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('analyse-news-article-y5_9', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('story-from-prompt-y5_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('homage-writing-y5_9', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('long-division-i-y5_9', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('algebra-introduction-y5_9', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('geometry-area-perimeter-y5_9', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('human-geography-y5_9', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('vs-physical-change-y5_9', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('hypothesis-test-y5_9', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('social-norms-pressures-y5_9', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('empathy-difference-y5_9', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('own-mental-health-y5_9', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('understand-consent-y5_9', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('handle-exclusion-constructively-y5_9', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('be-honest-friend-y5_9', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('astronomy-scale-model-y5_9', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('kombucha-or-kefir-y5_9', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('pressure-force-experiment-y5_9', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('dyeing-natural-plants-y5_9', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('micro-gardening-y5_9', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('own-calendar-week-y5_9', 'This develops the organisation and self-management that school increasingly demands.'),
  ('emergency-preparedness-y5_9', 'This develops the organisation and self-management that school increasingly demands.'),
  ('organise-sports-game-y6_0', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('swim-full-length-y6_0', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('cycling-route-y6_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('field-jumping-event-y6_0', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('skateboard-basic-tricks-y6_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('martial-arts-y6_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('choreograph-32-counts-y6_0', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('archery-y6_0', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('novel-y6_0', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('mosaic-tile-grouting-y6_0', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('paper-airplanes-aerodynamics-y6_0', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('sew-stuffed-animal-y6_0', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('digital-art-y6_0', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('leather-tooling-y6_0', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('read-non-fiction-book-y6_0', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-fairy-tale-y6_0', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('punctuation-colon-semicolon-y6_0', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('compound-complex-sentences-y6_0', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-song-y6_0', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('critical-reading-y6_0', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('start-reading-journal-y6_0', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('descriptive-writing-y6_0', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('percentages-amounts-y6_0', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('roman-numerals-y6_0', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('surface-area-y6_0', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('economics-supply-demand-y6_0', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('scientific-method-y6_0', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('human-rights-y6_0', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('self-assess-academic-work-y6_0', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('manage-long-term-projects-y6_0', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('cross-cultural-friendship-y6_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('compassion-vs-pity-y6_0', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('handle-public-mistake-y6_0', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('understand-privilege-y6_0', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('build-solar-oven-y6_0', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('grow-crystals-y6_0', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('make-pinhole-camera-y6_0', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('soap-making-y6_0', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('textile-printing-y6_0', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('budget-week-s-meals-y6_0', 'Independence and responsibility at this age build competence that carries well beyond the specific task.'),
  ('cook-from-recipe-y6_0', 'This develops the organisation and self-management that school increasingly demands.'),
  ('field-sport-y6_3', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('swim-flip-turn-y6_3', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('cycling-descent-control-y6_3', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('walkover-or-backbend-y6_3', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('athletics-800m-run-y6_3', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('basketball-dribble-shoot-y6_3', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('surfing-or-bodyboard-y6_3', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('martial-arts-sparring-y6_3', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('complete-short-story-y6_3', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('wearable-tech-design-y6_3', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('book-binding-y6_3', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('make-diorama-y6_3', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('rigid-heddle-loom-y6_3', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('calligraphy-full-alphabet-y6_3', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('novel-3-chapters-y6_3', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('socratic-seminar-y6_3', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('write-speech-y6_3', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('literary-devices-y6_3', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('letter-future-self-y6_3', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('analyse-speech-y6_3', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('collaborative-story-writing-y6_3', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('write-research-essay-y6_3', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('ratio-proportion-y6_3', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('angles-measuring-protractor-y6_3', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('prime-numbers-y6_3', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('volcanoes-plate-tectonics-y6_3', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('photosynthesis-equation-y6_3', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('historical-empathy-y6_3', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('manage-peer-pressure-y6_3', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('understand-anxiety-y6_3', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('loser-good-winner-y6_3', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('notice-systemic-unfairness-y6_3', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('own-mistakes-publicly-y6_3', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('reciprocity-relationships-y6_3', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('hydroponics-y6_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('electrolysis-y6_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('make-spectroscope-y6_3', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('felting-y6_3', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('ethnobotany-walk-y6_3', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('literacy-saving-interest-y6_3', 'Children who genuinely contribute at home tend to be more capable and more confident.'),
  ('cook-international-meal-y6_3', 'Independence and responsibility at this age build competence that carries well beyond the specific task.'),
  ('design-sport-y6_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('swimming-racing-dive-y6_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('cycle-touring-y6_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('advanced-gymnastics-sequence-y6_6', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('trail-running-y6_6', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('yoga-flow-y6_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('tennis-serve-y6_6', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('ultimate-frisbee-y6_6', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('science-fiction-story-y6_6', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('pottery-wheel-thrown-y6_6', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('knitting-first-garment-y6_6', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('build-app-y6_6', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('map-making-y6_6', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('make-documentary-y6_6', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('write-mystery-story-y6_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('debate-y6_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-personal-manifesto-y6_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('discuss-banned-book-y6_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('epistolary-story-y6_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('etymology-research-project-y6_6', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-found-poem-y6_6', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('understand-narrative-unreliability-y6_6', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('square-roots-y6_6', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('coordinate-geometry-y6_6', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('speed-distance-time-y6_6', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('genetics-introduction-y6_6', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('climate-science-y6_6', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('philosophy-mind-y6_6', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('emotional-regulation-toolkit-y6_6', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('understand-cognitive-biases-y6_6', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('practice-radical-honesty-y6_6', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('build-community-project-y6_6', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('understand-news-cycle-y6_6', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('comfort-someone-grief-y6_6', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('build-radio-y6_6', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('make-indigo-dye-y6_6', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('soil-science-investigation-y6_6', 'Sensory-rich activity gives children a break from cognitive demand while still developing skill.'),
  ('kite-from-scratch-y6_6', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('night-photography-y6_6', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('basic-first-aid-y6_6', 'Independence and responsibility at this age build competence that carries well beyond the specific task.'),
  ('manage-week-independently-y6_6', 'Children who genuinely contribute at home tend to be more capable and more confident.'),
  ('coach-younger-team-y6_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('marathon-y6_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('bicycle-maintenance-y6_9', 'This refines coordination and control, and gives your child the physical competence that sport and play at school will draw on.'),
  ('full-season-participation-y6_9', 'Skills at this age become more accurate and more strategic, and this is the kind of practice that develops both.'),
  ('swimming-medley-y6_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('mountain-bike-trail-y6_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('dance-choreograph-audience-y6_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('free-solo-climbing-y6_9', 'Physical activity now supports concentration, sleep and mood as much as it supports strength.'),
  ('write-novella-y6_9', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('working-model-engine-y6_9', 'The hand skills built here support handwriting, and handwriting fluency frees up attention for thinking.'),
  ('ceramics-glazing-firing-y6_9', 'This refines the precision your child now needs for writing, drawing and detailed work at school.'),
  ('wiring-simple-plug-y6_9', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('photography-composition-rules-y6_9', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('weave-rug-y6_9', 'Fine motor control at this age is about accuracy and endurance rather than basic ability.'),
  ('read-literature-y6_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('formal-argument-essay-y6_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('public-speaking-y6_9', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('write-research-paper-y6_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('translate-short-text-y6_9', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('study-present-person-y6_9', 'This supports the vocabulary and expression that school will increasingly demand.'),
  ('write-letter-authority-y6_9', 'Language now becomes a tool for thinking, explaining and reading, and this strengthens all three.'),
  ('discuss-dystopian-novel-y6_9', 'Being able to explain their thinking out loud helps children organise it, which is why talk matters at this age.'),
  ('algebra-linear-equations-y6_9', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('mean-median-mode-y6_9', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('understand-compound-interest-y6_9', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('ethics-trolley-problem-y6_9', 'This develops the planning and reasoning that increasingly demanding schoolwork will require.'),
  ('evolution-natural-selection-y6_9', 'At this age children can genuinely think through a problem, and doing so builds the habit of persisting with hard things.'),
  ('study-civilisation-y6_9', 'Understanding at this stage grows from working things out rather than being told the answer.'),
  ('build-personal-vision-y6_9', 'Your child can now reflect on their own behaviour, which makes real emotional learning possible.'),
  ('own-learning-style-y6_9', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('team-through-difficulty-y6_9', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('mental-health-continuum-y6_9', 'This supports the friendships, fairness and self-control that become central once children are in a classroom.'),
  ('give-something-back-y6_9', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('who-am-i-y6_9', 'Social and emotional skills at this age predict how school goes as much as academic ability does.'),
  ('rocketry-y6_9', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('bread-fermentation-y6_9', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('night-hike-y6_9', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('build-drone-y6_9', 'Physical and sensory input remains important at this age, particularly for children who sit still for long periods at school.'),
  ('make-graphic-novel-y6_9', 'This supports regulation and focus, which matters more once formal learning begins.'),
  ('responsible-technology-use-y6_9', 'Independence and responsibility at this age build competence that carries well beyond the specific task.'),
  ('button-hem-trousers-y6_9', 'This develops the organisation and self-management that school increasingly demands.')
) as v(id, new_benefit)
where a.id = v.id;
