-- Strips the generic "closer" sentence (one of a small recycled
-- pool of parenting-tip lines with no connection to the specific
-- activity) from the tail of `benefit`, leaving the genuine
-- domain/age-specific developmental claim — matching the field's own
-- documented shape ("One sentence: the developmental reason...").
-- Regenerated from content/activity_library.csv; batch 2/4.
update activities as a
set benefit = v.new_benefit
from (values
  ('sort-colours-m22_24', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('200-word-vocabulary-m22_24', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('two-three-word-phrases-m22_24', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('use-i-me-m22_24', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('ask-open-questions-m22_24', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('story-prediction-m22_24', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('name-colours-environment-m22_24', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('rhyming-play-m22_24', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('describe-daily-events-m22_24', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('sort-size-m22_24', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('sequence-daily-routine-m22_24', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('complete-simple-pattern-m22_24', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('concept-full-empty-m22_24', 'This builds early problem-solving at an age when persistence is short and everything is experimental.'),
  ('match-photo-person-m22_24', 'This builds early problem-solving at an age when persistence is short and everything is experimental.'),
  ('counting-one-to-one-correspondence-m22_24', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('sharing-practice-m22_24', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('cooperative-building-m22_24', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('feelings-vocabulary-m22_24', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('pretend-play-elaboration-m22_24', 'Toddlers have very big feelings and almost no ability to manage them, so this is about support rather than teaching.'),
  ('frustration-script-m22_24', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('apology-practice-m22_24', 'Toddlers have very big feelings and almost no ability to manage them, so this is about support rather than teaching.'),
  ('sensory-walk-barefoot-m22_24', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('mixing-colours-m22_24', 'Toddlers need a lot of sensory input, and providing it deliberately often reduces the seeking behaviour that looks like mischief.'),
  ('musical-instruments-exploration-m22_24', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('clay-detailed-work-m22_24', 'Messy, tactile play at this age builds tolerance that makes eating and dressing easier too.'),
  ('weighted-blanket-cuddle-m22_24', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('independent-dressing-m22_24', 'This builds genuine independence at an age when wanting to be independent is at its peak.'),
  ('toilet-training-awareness-m22_24', 'This builds genuine independence at an age when wanting to be independent is at its peak.'),
  ('jump-forward-m25_27', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('walk-balance-beam-m25_27', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('one-foot-i-m25_27', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('catch-bounced-ball-m25_27', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('pedal-steering-m25_27', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('animal-movement-play-m25_27', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('throw-overhand-m25_27', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('summersault-m25_27', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('drawing-plus-sign-m25_27', 'This strengthens the small muscles of the hand, which matters long before a pencil is ever picked up seriously.'),
  ('use-fork-independently-m25_27', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('dress-doll-m25_27', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('fold-paper-half-m25_27', 'This strengthens the small muscles of the hand, which matters long before a pencil is ever picked up seriously.'),
  ('sort-2-attributes-m25_27', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('lace-pattern-board-m25_27', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('tell-simple-story-m25_27', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('ask-answer-questions-m25_27', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('three-four-word-sentences-m25_27', 'Sentences are forming now, and children build them by hearing slightly more complex language than they can produce.'),
  ('rhyming-detection-m25_27', 'Sentences are forming now, and children build them by hearing slightly more complex language than they can produce.'),
  ('describe-picture-m25_27', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('first-last-name-m25_27', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('conversation-questions-m25_27', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('story-from-memory-m25_27', 'Sentences are forming now, and children build them by hearing slightly more complex language than they can produce.'),
  ('count-objects-5-m25_27', 'Sorting, counting and matching all begin here, and they begin through play rather than instruction.'),
  ('basic-opposites-m25_27', 'This is the age where children start to reason about why things happen, not just notice that they do.'),
  ('yesterday-today-m25_27', 'This is the age where children start to reason about why things happen, not just notice that they do.'),
  ('sort-4-categories-m25_27', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('pattern-extension-m25_27', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('simple-addition-concept-m25_27', 'Sorting, counting and matching all begin here, and they begin through play rather than instruction.'),
  ('imaginary-friend-engagement-m25_27', 'Regulation at this age still depends heavily on a calm adult nearby, and that is exactly as it should be.'),
  ('negotiate-trade-m25_27', 'Regulation at this age still depends heavily on a calm adult nearby, and that is exactly as it should be.'),
  ('brag-board-m25_27', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('role-play-m25_27', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('regulation-practice-pause-m25_27', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('how-others-feel-m25_27', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('tissue-paper-collage-m25_27', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('outdoor-water-play-m25_27', 'Sensory play remains genuinely developmental at this age, supporting both regulation and fine motor skill.'),
  ('texture-sorting-game-m25_27', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('proprioceptive-heavy-work-m25_27', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('spin-spot-m25_27', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('brush-teeth-independently-m25_27', 'Your toddler is now capable of real independence in daily routines, and doing so builds confidence as much as skill.'),
  ('toilet-training-m25_27', 'This reduces the daily friction of routines by giving your child a genuine role in them.'),
  ('hop-one-foot-m28_30', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('skip-i-m28_30', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('catch-thrown-ball-m28_30', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('pedal-brake-m28_30', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('climb-ladder-m28_30', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('jump-from-height-m28_30', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('balance-beam-m28_30', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('dodge-weave-game-m28_30', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('drawing-v-shape-m28_30', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('draw-person-i-m28_30', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('scissors-straight-line-m28_30', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('peel-stick-labels-m28_30', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('build-bridge-m28_30', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('string-small-beads-m28_30', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('500-word-vocabulary-m28_30', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('tell-stories-beginning-middle-end-m28_30', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('because-if-sentences-m28_30', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('how-something-works-m28_30', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('rhyme-production-m28_30', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('letter-name-recognition-m28_30', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('complex-question-response-m28_30', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('storytelling-from-memory-m28_30', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('count-10-meaning-m28_30', 'This is the age where children start to reason about why things happen, not just notice that they do.'),
  ('concept-same-different-m28_30', 'This is the age where children start to reason about why things happen, not just notice that they do.'),
  ('categorise-function-m28_30', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('on-under-behind-m28_30', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('morning-afternoon-evening-m28_30', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('simple-inference-m28_30', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('play-small-group-m28_30', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('express-feelings-words-m28_30', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('help-younger-child-m28_30', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('choose-activity-m28_30', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('deal-disappointment-script-m28_30', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('fairness-conversations-m28_30', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('cornstarch-goop-m28_30', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('sound-walk-m28_30', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('temperature-sensory-bin-m28_30', 'Sensory play remains genuinely developmental at this age, supporting both regulation and fine motor skill.'),
  ('yoga-kids-m28_30', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('top-or-gyroscope-m28_30', 'Sensory play remains genuinely developmental at this age, supporting both regulation and fine motor skill.'),
  ('pour-own-drink-m28_30', 'Your toddler is now capable of real independence in daily routines, and doing so builds confidence as much as skill.'),
  ('help-set-table-m28_30', 'Your toddler is now capable of real independence in daily routines, and doing so builds confidence as much as skill.'),
  ('hop-5-times-m31_33', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('broad-jump-m31_33', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('throw-vertical-target-m31_33', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('tricycle-fast-slow-m31_33', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('backward-balance-beam-m31_33', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('obstacle-course-run-m31_33', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('throw-run-combination-m31_33', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('marching-place-m31_33', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('copy-drawing-square-m31_33', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('draw-person-ii-m31_33', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('cut-curved-line-m31_33', 'This strengthens the small muscles of the hand, which matters long before a pencil is ever picked up seriously.'),
  ('button-large-buttons-m31_33', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('weave-paper-strips-m31_33', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('trace-letters-m31_33', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('700-900-word-vocabulary-m31_33', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('why-conversation-chain-m31_33', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('all-basic-colours-m31_33', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('use-plurals-correctly-m31_33', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('tense-regular-verbs-m31_33', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('what-you-see-m31_33', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('conditional-sentences-m31_33', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('letter-sound-introduction-m31_33', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('count-15-meaning-m31_33', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('all-basic-shapes-m31_33', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('more-fewer-m31_33', 'Sorting, counting and matching all begin here, and they begin through play rather than instruction.'),
  ('memory-game-m31_33', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('sequence-story-m31_33', 'Sorting, counting and matching all begin here, and they begin through play rather than instruction.'),
  ('first-middle-last-m31_33', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('friend-concept-m31_33', 'Regulation at this age still depends heavily on a calm adult nearby, and that is exactly as it should be.'),
  ('turns-group-game-m31_33', 'Regulation at this age still depends heavily on a calm adult nearby, and that is exactly as it should be.'),
  ('accepting-no-practice-m31_33', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('cooperative-drawing-m31_33', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('identify-emotions-others-m31_33', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('comfort-peer-distress-m31_33', 'Regulation at this age still depends heavily on a calm adult nearby, and that is exactly as it should be.'),
  ('mud-kitchen-play-m31_33', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('shadow-play-m31_33', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('magnet-exploration-m31_33', 'Sensory play remains genuinely developmental at this age, supporting both regulation and fine motor skill.'),
  ('rhythm-clapping-patterns-m31_33', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('blindfold-texture-guess-m31_33', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('prepare-simple-snack-m31_33', 'Competence at this age builds a sense of capability that praise alone cannot.'),
  ('dress-independently-m31_33', 'This reduces the daily friction of routines by giving your child a genuine role in them.'),
  ('skip-m34_36', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('throw-catch-iii-m34_36', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('hop-10-times-m34_36', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('jump-over-line-m34_36', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('balance-one-foot-m34_36', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('dribble-ball-m34_36', 'Movement at this age is how the body''s control systems get calibrated, and children who move more move better.'),
  ('move-music-i-m34_36', 'This is a good age for challenging the balance system, because the body is stable enough to try and still learning fast.'),
  ('gallop-object-hand-m34_36', 'Your toddler is becoming genuinely capable physically, and this builds the strength and coordination that running, climbing and jumping all need.'),
  ('copy-drawing-triangle-m34_36', 'This strengthens the small muscles of the hand, which matters long before a pencil is ever picked up seriously.'),
  ('draw-person-m34_36', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('copy-first-name-m34_36', 'Hand control is sharpening quickly now, and this builds toward the precision that drawing, cutting and dressing need.'),
  ('child-scissors-shape-m34_36', 'This strengthens the small muscles of the hand, which matters long before a pencil is ever picked up seriously.'),
  ('paper-into-envelope-m34_36', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('complex-block-structures-m34_36', 'Your toddler''s hands can now do far more than a year ago, and this stretches that capability a little further.'),
  ('1000-word-vocabulary-m34_36', 'Sentences are forming now, and children build them by hearing slightly more complex language than they can produce.'),
  ('retell-story-m34_36', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('past-future-tense-m34_36', 'Sentences are forming now, and children build them by hearing slightly more complex language than they can produce.'),
  ('something-works-i-m34_36', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('letter-sound-game-m34_36', 'This is a period of rapid vocabulary growth, and conversation is what fuels it.'),
  ('5-word-sentences-m34_36', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('is-x-better-m34_36', 'Language at this age develops through back-and-forth exchanges, where your toddler gets a real turn.'),
  ('rhyme-word-family-m34_36', 'Sentences are forming now, and children build them by hearing slightly more complex language than they can produce.'),
  ('count-20-m34_36', 'Sorting, counting and matching all begin here, and they begin through play rather than instruction.'),
  ('concept-zero-m34_36', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('name-10-colours-m34_36', 'Sorting, counting and matching all begin here, and they begin through play rather than instruction.'),
  ('days-week-introduction-m34_36', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('pattern-prediction-m34_36', 'This is the age where children start to reason about why things happen, not just notice that they do.'),
  ('cause-effect-explanation-m34_36', 'Your toddler can now hold an idea in mind and work toward it, which makes this kind of thinking activity genuinely useful.'),
  ('cooperative-game-i-m34_36', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('conflict-resolution-script-m34_36', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('own-feelings-early-m34_36', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('apology-empathy-m34_36', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('winning-losing-gracefully-m34_36', 'Your toddler is starting to notice other people''s feelings, which is the beginning of empathy.'),
  ('best-friend-identification-m34_36', 'This builds the emotional vocabulary and self-control that make the preschool years easier.'),
  ('resist-and-wait-practice-m34_36', 'Regulation at this age still depends heavily on a calm adult nearby, and that is exactly as it should be.'),
  ('slime-making-m34_36', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('sensory-story-walk-m34_36', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('nature-printing-m34_36', 'Sensory play remains genuinely developmental at this age, supporting both regulation and fine motor skill.'),
  ('blindfold-object-guess-m34_36', 'This helps your toddler''s nervous system distinguish between different sensations, which supports focus and calm.'),
  ('rhythm-band-m34_36', 'Rich sensory experience at this stage feeds language too, because it gives children something worth describing.'),
  ('simple-self-care-sequence-m34_36', 'This reduces the daily friction of routines by giving your child a genuine role in them.'),
  ('help-household-chores-m34_36', 'Competence at this age builds a sense of capability that praise alone cannot.'),
  ('skip-distance-challenge-y3_0', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('gallop-relay-y3_0', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('throw-overhand-distance-y3_0', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('hop-non-dominant-foot-y3_0', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('pump-swing-y3_0', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('jump-rope-y3_0', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('catch-one-hand-y3_0', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('steering-obstacle-course-y3_0', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('copy-drawing-diamond-y3_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('write-first-name-y3_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('craft-project-y3_0', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('use-ruler-y3_0', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('fold-paper-y3_0', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('braid-3-strands-y3_0', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('story-5-events-y3_0', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('ask-answer-why-y3_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('full-alphabet-y3_0', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('describe-yesterday-detail-y3_0', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('compound-sentences-y3_0', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('word-families-y3_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('conversations-adults-y3_0', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('read-environmental-print-y3_0', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('addition-5-y3_0', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('subtraction-5-y3_0', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('measurement-comparison-y3_0', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('days-week-y3_0', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('pattern-aabbc-y3_0', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('map-making-i-y3_0', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('cooperative-building-project-y3_0', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('conflict-resolution-role-play-y3_0', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('emotion-intensity-scale-y3_0', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('plan-activity-together-y3_0', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('appreciate-differences-y3_0', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('celebrate-others-successes-y3_0', 'Children this age can begin to name feelings and see another point of view, with support.'),
  ('clay-sculpture-y3_0', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('sound-mapping-y3_0', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('texture-collage-y3_0', 'Hands-on sensory work builds both discrimination and the vocabulary to describe what they notice.'),
  ('cooking-mix-pour-y3_0', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('mindful-breathing-y3_0', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('dress-completely-independently-y3_0', 'This develops the independence that starting school will require.'),
  ('make-own-breakfast-y3_0', 'This develops the independence that starting school will require.'),
  ('skip-change-direction-y3_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('kick-moving-ball-y3_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('hop-distance-y3_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('beam-walk-backward-y3_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('vs-jog-signal-y3_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('catch-both-hands-y3_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('jump-rope-ii-y3_3', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('side-slide-steps-y3_3', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('copy-initials-y3_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('mosaic-tile-placement-y3_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('use-stapler-y3_3', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('zig-zag-cutting-y3_3', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('weave-fabric-strips-y3_3', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('pin-and-thread-simple-embroidery-y3_3', 'Precision at this age comes from doing things with the hands repeatedly, not from being taught how.'),
  ('1500-word-vocabulary-y3_3', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('write-dictated-sentence-y3_3', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('simple-c-v-c-words-y3_3', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('use-conjunctions-y3_3', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('explain-process-step-by-step-y3_3', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('conversation-repair-y3_3', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('news-sharing-y3_3', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('simple-crossword-y3_3', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('add-within-10-y3_3', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('subtract-within-10-y3_3', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('days-week-order-y3_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('seasons-concept-y3_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('sort-graph-y3_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('living-non-living-y3_3', 'Thinking skills at this stage develop through exploration and questions rather than through being taught answers.'),
  ('verbally-before-escalation-y3_3', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('introduce-compromise-y3_3', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('identity-i-am-y3_3', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('friendship-maintenance-y3_3', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('handle-disappointment-script-y3_3', 'This builds emotional understanding and social confidence at the age when both start to matter outside home.'),
  ('gratitude-practice-y3_3', 'Friendships become genuinely important now, and the skills involved are learnable rather than automatic.'),
  ('cooking-sensory-experience-y3_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('ice-melt-science-y3_3', 'Sensory experience supports attention and regulation, and children this age still need plenty of it.'),
  ('weaving-natural-materials-y3_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('mindful-listening-y3_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('or-torch-play-y3_3', 'This gives your child varied physical and sensory input, which supports concentration afterwards.'),
  ('independent-morning-routine-y3_3', 'This develops the independence that starting school will require.'),
  ('responsible-one-chore-y3_3', 'This develops the independence that starting school will require.'),
  ('over-moving-object-y3_6', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('dribble-run-y3_6', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('one-leg-balance-y3_6', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('summersault-independently-y3_6', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('tandem-walk-y3_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('gallop-music-y3_6', 'Physical confidence is being set now, and children who feel capable in their bodies at this age tend to stay active later.'),
  ('target-throwing-y3_6', 'At this age motor skills become more precise and more deliberate, and practice is what sharpens them.'),
  ('jumping-jacks-y3_6', 'This builds coordination and control at exactly the point where a child can start to see their own improvement.'),
  ('letter-formation-practice-y3_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('watercolour-painting-y3_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('weaving-y3_6', 'Children need strong, controlled hands before letter formation makes sense, and this builds exactly that.'),
  ('use-hole-punch-y3_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('cut-spiral-y3_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('thin-clay-snake-y3_6', 'This develops the hand strength and control that writing will demand, well before formal writing begins.'),
  ('read-simple-sentences-y3_6', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('write-simple-words-y3_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('use-adjectives-adverbs-y3_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('tell-joke-y3_6', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('listen-summarise-y3_6', 'Vocabulary at this age is one of the strongest predictors of later reading, and it grows through talk and stories.'),
  ('10-sight-words-y3_6', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('give-directions-someone-y3_6', 'Children this age learn language best through genuine conversation rather than through being quizzed.'),
  ('debate-two-sides-y3_6', 'This builds the language your child will use to reason, explain and eventually read.'),
  ('addition-subtraction-10-y3_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.'),
  ('even-odd-numbers-y3_6', 'Children this age learn concepts by handling them physically before they can handle them abstractly.'),
  ('months-year-y3_6', 'This builds the reasoning and problem-solving that school will draw on, in a form your child can actually enjoy.')
) as v(id, new_benefit)
where a.id = v.id;
