-- Strips the generic "closer" sentence (one of a small recycled
-- pool of parenting-tip lines with no connection to the specific
-- activity) from the tail of `benefit`, leaving the genuine
-- domain/age-specific developmental claim — matching the field's own
-- documented shape ("One sentence: the developmental reason...").
-- Regenerated from content/activity_library.csv; batch 1/4.
update activities as a
set benefit = v.new_benefit
from (values
  ('chest-tummy-time-m0_3', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('floor-tummy-time-m0_3', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('bicycle-legs-m0_3', 'Babies this age cannot yet control their movements, so this is about giving the body the right opportunities rather than teaching a skill.'),
  ('arm-stretch-midline-m0_3', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('visual-tracking-card-m0_3', 'Every small movement now is building the neck, shoulder and trunk strength that rolling and sitting will later depend on.'),
  ('supported-upright-hold-m0_3', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('leg-kicking-scarf-m0_3', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('side-lying-practice-m0_3', 'Every small movement now is building the neck, shoulder and trunk strength that rolling and sitting will later depend on.'),
  ('grip-my-finger-m0_3', 'Your baby''s hands are mostly working on reflex at this stage, and this gently invites them to open, feel and eventually grasp on purpose.'),
  ('hand-massage-m0_3', 'Before a baby can reach for anything they need to discover their hands exist, and this is part of that discovery.'),
  ('open-fist-m0_3', 'Before a baby can reach for anything they need to discover their hands exist, and this is part of that discovery.'),
  ('bringing-hands-middle-m0_3', 'Before a baby can reach for anything they need to discover their hands exist, and this is part of that discovery.'),
  ('gentle-wrist-turns-m0_3', 'Hand movements are still involuntary now, so this is about sensation and awareness rather than skill.'),
  ('holding-soft-toy-m0_3', 'Before a baby can reach for anything they need to discover their hands exist, and this is part of that discovery.'),
  ('narrate-every-routine-m0_3', 'Long before your baby says a word, they are learning the rhythm, pitch and melody of your language, and that learning happens now.'),
  ('lori-song-m0_3', 'Your voice is the most important sound in your baby''s world, and every bit of talk builds the foundation for later language.'),
  ('sound-baby-makes-m0_3', 'Babies absorb the patterns of speech months before they can produce any of it, which is why talking to them matters so early.'),
  ('wait-and-respond-talking-game-m0_3', 'Long before your baby says a word, they are learning the rhythm, pitch and melody of your language, and that learning happens now.'),
  ('name-recognition-distance-m0_3', 'Long before your baby says a word, they are learning the rhythm, pitch and melody of your language, and that learning happens now.'),
  ('sound-exploration-m0_3', 'Babies absorb the patterns of speech months before they can produce any of it, which is why talking to them matters so early.'),
  ('sing-song-baby-talk-m0_3', 'Your voice is the most important sound in your baby''s world, and every bit of talk builds the foundation for later language.'),
  ('read-aloud-m0_3', 'Babies absorb the patterns of speech months before they can produce any of it, which is why talking to them matters so early.'),
  ('high-contrast-cards-m0_3', 'Newborn vision and attention are still developing, and this gives them exactly the kind of input that helps them along.'),
  ('face-gazing-m0_3', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('mirror-gazing-m0_3', 'At this stage thinking looks like looking: attention, recognition and noticing what is familiar.'),
  ('disappearing-face-peek-m0_3', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('light-shadow-m0_3', 'Newborn vision and attention are still developing, and this gives them exactly the kind of input that helps them along.'),
  ('b-w-pattern-book-m0_3', 'Newborn vision and attention are still developing, and this gives them exactly the kind of input that helps them along.'),
  ('skin-to-skin-hold-m0_3', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('smile-mirroring-m0_3', 'This is the beginning of the relationship, and at this age closeness and responsiveness are the whole task.'),
  ('responsive-holding-m0_3', 'This is the beginning of the relationship, and at this age closeness and responsiveness are the whole task.'),
  ('emotional-narration-m0_3', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('caregiver-rotation-m0_3', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('calm-modelling-m0_3', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('tel-maalish-m0_3', 'Sensory experience is how a newborn learns about their own body and the world around it.'),
  ('feel-different-things-m0_3', 'Your baby''s nervous system is learning to make sense of touch, sound and movement, and gentle input helps it organise.'),
  ('outdoor-air-light-m0_3', 'Sensory experience is how a newborn learns about their own body and the world around it.'),
  ('water-temperature-play-m0_3', 'Sensory experience is how a newborn learns about their own body and the world around it.'),
  ('humming-chest-m0_3', 'Sensory experience is how a newborn learns about their own body and the world around it.'),
  ('baby-s-hunger-signs-m0_3', 'Daily care routines are your baby''s first experience of predictability, and predictability is what makes them feel safe.'),
  ('watching-tired-signs-m0_3', 'At this age self-care is entirely done for your baby, and the value lies in how calm and consistent it feels.'),
  ('tummy-time-toy-m4_6', 'Every small movement now is building the neck, shoulder and trunk strength that rolling and sitting will later depend on.'),
  ('rolling-facilitation-m4_6', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('floor-roll-practice-m4_6', 'Babies this age cannot yet control their movements, so this is about giving the body the right opportunities rather than teaching a skill.'),
  ('supported-sitting-m4_6', 'Every small movement now is building the neck, shoulder and trunk strength that rolling and sitting will later depend on.'),
  ('prop-up-forearms-m4_6', 'Babies this age cannot yet control their movements, so this is about giving the body the right opportunities rather than teaching a skill.'),
  ('against-my-hands-m4_6', 'Babies this age cannot yet control their movements, so this is about giving the body the right opportunities rather than teaching a skill.'),
  ('bounce-lap-m4_6', 'In these first months your baby is working on the very first physical task of life: holding their own head steady and learning that their body belongs to them.'),
  ('tummy-time-mirror-m4_6', 'Babies this age cannot yet control their movements, so this is about giving the body the right opportunities rather than teaching a skill.'),
  ('reach-hanging-object-m4_6', 'Your baby''s hands are mostly working on reflex at this stage, and this gently invites them to open, feel and eventually grasp on purpose.'),
  ('two-handed-grasp-m4_6', 'Before a baby can reach for anything they need to discover their hands exist, and this is part of that discovery.'),
  ('object-transfer-observation-m4_6', 'Your baby''s hands are mostly working on reflex at this stage, and this gently invites them to open, feel and eventually grasp on purpose.'),
  ('shake-listen-m4_6', 'Hand movements are still involuntary now, so this is about sensation and awareness rather than skill.'),
  ('crinkle-paper-explore-m4_6', 'Hand movements are still involuntary now, so this is about sensation and awareness rather than skill.'),
  ('press-feel-m4_6', 'Hand movements are still involuntary now, so this is about sensation and awareness rather than skill.'),
  ('babble-echo-session-m4_6', 'Long before your baby says a word, they are learning the rhythm, pitch and melody of your language, and that learning happens now.'),
  ('makes-baby-laugh-m4_6', 'Your voice is the most important sound in your baby''s world, and every bit of talk builds the foundation for later language.'),
  ('consonant-introduction-m4_6', 'Your voice is the most important sound in your baby''s world, and every bit of talk builds the foundation for later language.'),
  ('talk-both-languages-m4_6', 'Your voice is the most important sound in your baby''s world, and every bit of talk builds the foundation for later language.'),
  ('photo-person-i-m4_6', 'Your voice is the most important sound in your baby''s world, and every bit of talk builds the foundation for later language.'),
  ('music-variety-session-m4_6', 'Babies absorb the patterns of speech months before they can produce any of it, which is why talking to them matters so early.'),
  ('name-moving-m4_6', 'Long before your baby says a word, they are learning the rhythm, pitch and melody of your language, and that learning happens now.'),
  ('pause-song-m4_6', 'Long before your baby says a word, they are learning the rhythm, pitch and melody of your language, and that learning happens now.'),
  ('peekaboo-m4_6', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('push-see-m4_6', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('out-box-m4_6', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('follow-my-point-m4_6', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('smooth-texture-game-m4_6', 'Your baby''s brain is building its very first expectations about the world, mostly through what they see and hear repeatedly.'),
  ('what-s-coming-game-m4_6', 'Newborn vision and attention are still developing, and this gives them exactly the kind of input that helps them along.'),
  ('social-smile-response-m4_6', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('stranger-presence-practice-m4_6', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('listening-no-m4_6', 'Every time you respond to your baby, you are teaching them that the world is reliable, which is the foundation of secure attachment.'),
  ('practising-goodbye-m4_6', 'This is the beginning of the relationship, and at this age closeness and responsiveness are the whole task.'),
  ('naming-feelings-m4_6', 'Your baby cannot calm themselves yet, so being soothed by you is how their nervous system learns what calm feels like.'),
  ('look-this-together-m4_6', 'Every time you respond to your baby, you are teaching them that the world is reliable, which is the foundation of secure attachment.'),
  ('water-kicking-m4_6', 'Calm, predictable sensory input helps a young baby settle and regulate.'),
  ('sensory-walk-m4_6', 'Calm, predictable sensory input helps a young baby settle and regulate.'),
  ('varied-food-textures-m4_6', 'Sensory experience is how a newborn learns about their own body and the world around it.'),
  ('dance-sway-m4_6', 'Sensory experience is how a newborn learns about their own body and the world around it.'),
  ('temperature-contrast-hands-m4_6', 'Calm, predictable sensory input helps a young baby settle and regulate.'),
  ('before-every-feed-m4_6', 'At this age self-care is entirely done for your baby, and the value lies in how calm and consistent it feels.'),
  ('before-every-nap-m4_6', 'Daily care routines are your baby''s first experience of predictability, and predictability is what makes them feel safe.'),
  ('sitting-balance-challenge-m7_9', 'This is the stage where babies begin to move themselves through the world, and every attempt builds the strength for the next milestone.'),
  ('crawling-encouragement-m7_9', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('all-fours-rocking-m7_9', 'This is the stage where babies begin to move themselves through the world, and every attempt builds the strength for the next milestone.'),
  ('obstacle-crawl-m7_9', 'This is the stage where babies begin to move themselves through the world, and every attempt builds the strength for the next milestone.'),
  ('pull-stand-m7_9', 'Crawling, pulling up and cruising all arrive in this window, and they arrive through practice rather than instruction.'),
  ('pivot-tummy-time-m7_9', 'This is the stage where babies begin to move themselves through the world, and every attempt builds the strength for the next milestone.'),
  ('walking-hold-m7_9', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('stair-climbing-m7_9', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('pinch-pick-up-m7_9', 'The finger and thumb grip that will later hold a spoon and a pencil begins forming in this window.'),
  ('object-container-m7_9', 'Your baby is learning to let go on purpose, which is a genuinely harder skill than picking something up.'),
  ('banging-objects-together-m7_9', 'This is when grasping becomes deliberate rather than reflexive, and every reach and release is practice.'),
  ('page-turning-m7_9', 'This is when grasping becomes deliberate rather than reflexive, and every reach and release is practice.'),
  ('stack-topple-m7_9', 'This is when grasping becomes deliberate rather than reflexive, and every reach and release is practice.'),
  ('between-two-containers-m7_9', 'This is when grasping becomes deliberate rather than reflexive, and every reach and release is practice.'),
  ('echo-baby-s-babbling-m7_9', 'Understanding runs well ahead of speaking at this age, and this builds the comprehension that first words will grow from.'),
  ('respond-name-m7_9', 'This is the window where gestures and sounds start carrying meaning, which is language beginning.'),
  ('gesture-introduction-m7_9', 'Babbling is real practice for speech, and responding to it teaches your baby that sounds get answers.'),
  ('point-name-m7_9', 'Babbling is real practice for speech, and responding to it teaches your baby that sounds get answers.'),
  ('book-naming-session-m7_9', 'Understanding runs well ahead of speaking at this age, and this builds the comprehension that first words will grow from.'),
  ('simple-instruction-practice-m7_9', 'Understanding runs well ahead of speaking at this age, and this builds the comprehension that first words will grow from.'),
  ('babble-conversation-record-m7_9', 'This is the window where gestures and sounds start carrying meaning, which is language beginning.'),
  ('name-body-parts-m7_9', 'Understanding runs well ahead of speaking at this age, and this builds the comprehension that first words will grow from.'),
  ('find-hidden-toy-m7_9', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('cloth-get-toy-m7_9', 'Thinking at this age is entirely hands-on, built by doing rather than by being shown.'),
  ('see-what-happens-m7_9', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('sort-big-small-m7_9', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('imitation-game-m7_9', 'This is when babies begin to understand that their actions cause things to happen, and they test it endlessly.'),
  ('object-memory-game-m7_9', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('someone-new-slowly-m7_9', 'Your baby now knows familiar faces from unfamiliar ones, and this helps them navigate that with you close by.'),
  ('honouring-stop-signal-m7_9', 'Your baby now knows familiar faces from unfamiliar ones, and this helps them navigate that with you close by.'),
  ('longer-goodbye-practice-m7_9', 'This supports the attachment that will let your baby explore confidently later.'),
  ('mirror-game-together-m7_9', 'Social games and shared attention become possible around now, and they are how relationships start being two-way.'),
  ('favourite-laughs-list-m7_9', 'Social games and shared attention become possible around now, and they are how relationships start being two-way.'),
  ('did-mama-go-m7_9', 'Social games and shared attention become possible around now, and they are how relationships start being two-way.'),
  ('textured-surface-crawling-m7_9', 'Sensory play at this stage is genuine learning, not just entertainment.'),
  ('water-play-m7_9', 'Sensory play at this stage is genuine learning, not just entertainment.'),
  ('nature-texture-explore-m7_9', 'This gives your baby the range of sensations their developing nervous system needs to calibrate.'),
  ('mouth-exploration-m7_9', 'Babies explore mainly through touch and mouth at this age, and varied input helps the sensory system develop.'),
  ('sound-localisation-game-m7_9', 'Babies explore mainly through touch and mouth at this age, and varied input helps the sensory system develop.'),
  ('spoon-introduction-m7_9', 'Letting your baby take part, even when it is slower, is what builds the skill.'),
  ('cup-introduction-m7_9', 'Your baby is starting to participate in routines rather than just receive them, which is where independence begins.'),
  ('cruising-along-furniture-m10_12', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('steps-between-points-m10_12', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('standing-balance-challenge-m10_12', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('stair-descent-practice-m10_12', 'Crawling, pulling up and cruising all arrive in this window, and they arrive through practice rather than instruction.'),
  ('ball-kicking-m10_12', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('carry-while-walking-m10_12', 'Crawling, pulling up and cruising all arrive in this window, and they arrive through practice rather than instruction.'),
  ('push-along-toy-walk-m10_12', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('rough-ground-walking-m10_12', 'Your baby is learning what their body can do, and the falls and wobbles are part of how that map gets built.'),
  ('object-pinch-practice-m10_12', 'The finger and thumb grip that will later hold a spoon and a pencil begins forming in this window.'),
  ('scribble-crayon-m10_12', 'Your baby is learning to let go on purpose, which is a genuinely harder skill than picking something up.'),
  ('stacking-2-3-blocks-m10_12', 'This is when grasping becomes deliberate rather than reflexive, and every reach and release is practice.'),
  ('post-into-container-m10_12', 'The finger and thumb grip that will later hold a spoon and a pencil begins forming in this window.'),
  ('turn-pages-m10_12', 'The finger and thumb grip that will later hold a spoon and a pencil begins forming in this window.'),
  ('unscrew-lid-m10_12', 'This is when grasping becomes deliberate rather than reflexive, and every reach and release is practice.'),
  ('mama-dada-meaning-m10_12', 'Babbling is real practice for speech, and responding to it teaches your baby that sounds get answers.'),
  ('first-word-inventory-m10_12', 'Understanding runs well ahead of speaking at this age, and this builds the comprehension that first words will grow from.'),
  ('expand-every-utterance-m10_12', 'Babbling is real practice for speech, and responding to it teaches your baby that sounds get answers.'),
  ('bye-bye-gesture-m10_12', 'This is the window where gestures and sounds start carrying meaning, which is language beginning.'),
  ('point-name-response-m10_12', 'Babbling is real practice for speech, and responding to it teaches your baby that sounds get answers.'),
  ('follow-simple-instruction-m10_12', 'Understanding runs well ahead of speaking at this age, and this builds the comprehension that first words will grow from.'),
  ('nursery-rhymes-actions-m10_12', 'Babbling is real practice for speech, and responding to it teaches your baby that sounds get answers.'),
  ('3-body-parts-m10_12', 'This is the window where gestures and sounds start carrying meaning, which is language beginning.'),
  ('is-it-under-m10_12', 'This is when babies begin to understand that their actions cause things to happen, and they test it endlessly.'),
  ('copy-mama-s-chore-m10_12', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('simple-puzzle-m10_12', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('object-under-cup-m10_12', 'Thinking at this age is entirely hands-on, built by doing rather than by being shown.'),
  ('let-s-pretend-m10_12', 'Thinking at this age is entirely hands-on, built by doing rather than by being shown.'),
  ('open-box-puzzle-m10_12', 'Your baby is discovering that things still exist when they cannot see them, which is one of the biggest ideas of the first year.'),
  ('affection-initiation-m10_12', 'Your baby now knows familiar faces from unfamiliar ones, and this helps them navigate that with you close by.'),
  ('limit-testing-observation-m10_12', 'Social games and shared attention become possible around now, and they are how relationships start being two-way.'),
  ('empathy-seed-m10_12', 'Your baby now knows familiar faces from unfamiliar ones, and this helps them navigate that with you close by.'),
  ('short-separation-practice-m10_12', 'Social games and shared attention become possible around now, and they are how relationships start being two-way.'),
  ('alongside-another-child-m10_12', 'Social games and shared attention become possible around now, and they are how relationships start being two-way.'),
  ('social-game-repetition-m10_12', 'Your baby now knows familiar faces from unfamiliar ones, and this helps them navigate that with you close by.'),
  ('sensory-bin-introduction-m10_12', 'Sensory play at this stage is genuine learning, not just entertainment.'),
  ('outdoor-ground-texture-m10_12', 'Sensory play at this stage is genuine learning, not just entertainment.'),
  ('music-movement-m10_12', 'Babies explore mainly through touch and mouth at this age, and varied input helps the sensory system develop.'),
  ('whole-body-movement-play-m10_12', 'Sensory play at this stage is genuine learning, not just entertainment.'),
  ('messy-play-introduction-m10_12', 'This gives your baby the range of sensations their developing nervous system needs to calibrate.'),
  ('spoon-practice-self-feed-m10_12', 'Your baby is starting to participate in routines rather than just receive them, which is where independence begins.'),
  ('shoes-socks-off-m10_12', 'Early self-feeding and cooperation with dressing start now, messily and imperfectly.'),
  ('walk-uneven-ground-m13_15', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('climbing-low-furniture-m13_15', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('squat-pick-up-m13_15', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('kick-ball-forward-m13_15', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('throw-ball-m13_15', 'At this age balance is still developing, and each attempt refines it a little further.'),
  ('walk-carry-m13_15', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('dance-freely-m13_15', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('stair-up-down-m13_15', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('crayon-mark-making-m13_15', 'Fine motor skill at this stage is built through play rather than practice, and this offers plenty of both.'),
  ('stacking-4-blocks-m13_15', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('shape-sorter-m13_15', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('bead-threading-m13_15', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('fill-pour-m13_15', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('peel-stickers-m13_15', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('10-word-vocabulary-m13_15', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('two-word-combination-watch-m13_15', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('5-body-parts-m13_15', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('picture-book-naming-m13_15', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('follow-2-step-instruction-m13_15', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('pretend-telephone-call-m13_15', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('expand-add-more-m13_15', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('sing-and-fill-m13_15', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('simple-pretend-sequence-m13_15', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('find-matching-pair-m13_15', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('under-two-cups-m13_15', 'This builds early problem-solving at an age when persistence is short and everything is experimental.'),
  ('sort-colour-m13_15', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('early-number-concepts-m13_15', 'This builds early problem-solving at an age when persistence is short and everything is experimental.'),
  ('ramp-roll-m13_15', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('play-beside-peer-m13_15', 'Toddlers have very big feelings and almost no ability to manage them, so this is about support rather than teaching.'),
  ('tantrums-as-communication-m13_15', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('mine-acknowledgement-m13_15', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('comfort-object-introduction-m13_15', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('proud-moments-response-m13_15', 'Toddlers have very big feelings and almost no ability to manage them, so this is about support rather than teaching.'),
  ('independence-play-m13_15', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('messy-sensory-play-m13_15', 'Messy, tactile play at this age builds tolerance that makes eating and dressing easier too.'),
  ('nature-walk-collect-m13_15', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('rhythm-instruments-m13_15', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('spinning-rolling-m13_15', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('atta-dough-play-m13_15', 'Toddlers need a lot of sensory input, and providing it deliberately often reduces the seeking behaviour that looks like mischief.'),
  ('spoon-use-practice-m13_15', 'This builds genuine independence at an age when wanting to be independent is at its peak.'),
  ('partial-dressing-help-m13_15', 'Toddlers want to do things themselves, and channelling that into real self-care tasks works with the drive rather than against it.'),
  ('running-practice-m16_18', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('walk-up-stairs-m16_18', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('kick-ball-aim-m16_18', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('jump-off-step-m16_18', 'At this age balance is still developing, and each attempt refines it a little further.'),
  ('ladder-slide-m16_18', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('pedal-m16_18', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('balance-beam-walking-m16_18', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('carry-heavy-load-m16_18', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('drawing-lines-m16_18', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('unscrew-screw-lids-m16_18', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('stacking-6-blocks-m16_18', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('tear-paper-m16_18', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('string-beads-m16_18', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('puzzle-m16_18', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('20-50-word-vocabulary-m16_18', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('two-word-combinations-m16_18', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('what-s-that-response-m16_18', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('story-telling-m16_18', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('animal-sounds-game-m16_18', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('action-word-focus-m16_18', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('reading-together-daily-m16_18', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('singing-along-m16_18', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('simple-pretend-cooking-m16_18', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('sort-shape-m16_18', 'This builds early problem-solving at an age when persistence is short and everything is experimental.'),
  ('picture-to-object-match-m16_18', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('order-completion-m16_18', 'This builds early problem-solving at an age when persistence is short and everything is experimental.'),
  ('count-objects-m16_18', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('problem-solving-unstick-m16_18', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('emotion-coaching-m16_18', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('feelings-chart-introduction-m16_18', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('practice-goodbye-ritual-m16_18', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('cooperative-game-m16_18', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('show-empathy-books-m16_18', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('household-helper-m16_18', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('sensory-bin-m16_18', 'Messy, tactile play at this age builds tolerance that makes eating and dressing easier too.'),
  ('outdoor-barefoot-walking-m16_18', 'Toddlers need a lot of sensory input, and providing it deliberately often reduces the seeking behaviour that looks like mischief.'),
  ('or-dough-play-m16_18', 'Toddlers need a lot of sensory input, and providing it deliberately often reduces the seeking behaviour that looks like mischief.'),
  ('sound-discrimination-m16_18', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('blanket-roll-burrito-m16_18', 'Messy, tactile play at this age builds tolerance that makes eating and dressing easier too.'),
  ('spoon-fork-independence-m16_18', 'Skills like these take far longer when a toddler does them, and that time is the investment.'),
  ('washing-hands-routine-m16_18', 'Skills like these take far longer when a toddler does them, and that time is the investment.'),
  ('running-direction-changes-m19_21', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('jump-both-feet-m19_21', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('up-down-stairs-m19_21', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('kick-stationary-ball-m19_21', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('one-foot-briefly-m19_21', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('climbing-frames-m19_21', 'At this age balance is still developing, and each attempt refines it a little further.'),
  ('throwing-target-m19_21', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('ride-on-steer-m19_21', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('draw-vertical-line-m19_21', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('copy-circle-m19_21', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('stack-8-blocks-m19_21', 'Fine motor skill at this stage is built through play rather than practice, and this offers plenty of both.'),
  ('cut-child-scissors-m19_21', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('peg-pegboard-m19_21', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('lace-large-holes-m19_21', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('50-100-word-vocabulary-m19_21', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('three-word-phrases-m19_21', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('refer-self-name-m19_21', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('ask-why-game-m19_21', 'Your toddler understands much more than they can say, and this closes that gap.'),
  ('story-re-tell-m19_21', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('colour-naming-focus-m19_21', 'First words appear in this window, and they appear faster in children who are talked with rather than talked at.'),
  ('2-step-instruction-i-m19_21', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('conversation-practice-m19_21', 'Vocabulary at this age grows through repeated, everyday exchanges far more than through teaching.'),
  ('cause-effect-multi-step-m19_21', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('animals-vs-food-m19_21', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('sequence-3-events-m19_21', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('puzzle-6-8-pieces-m19_21', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('count-1-5-objects-m19_21', 'Understanding at this stage is built through direct experience, repeated many times.'),
  ('memory-card-match-m19_21', 'Toddlers learn by trying things and seeing what happens, and this gives them something worth investigating.'),
  ('emotion-management-practice-m19_21', 'Your toddler is discovering they are a separate person with their own wants, which is why this stage is intense.'),
  ('turn-taking-games-m19_21', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('empathy-practice-m19_21', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('pretend-play-social-m19_21', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('self-advocacy-seed-m19_21', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('comfort-skill-building-m19_21', 'Emotional skills at this age are learned by being helped through feelings, over and over.'),
  ('water-transfer-play-m19_21', 'This supports the sensory processing that underlies calm, settled behaviour.'),
  ('atta-dough-shapes-m19_21', 'Messy, tactile play at this age builds tolerance that makes eating and dressing easier too.'),
  ('nature-scavenger-hunt-m19_21', 'Toddlers need a lot of sensory input, and providing it deliberately often reduces the seeking behaviour that looks like mischief.'),
  ('bubble-play-m19_21', 'Messy, tactile play at this age builds tolerance that makes eating and dressing easier too.'),
  ('paint-hands-m19_21', 'Toddlers need a lot of sensory input, and providing it deliberately often reduces the seeking behaviour that looks like mischief.'),
  ('dressing-participation-m19_21', 'Toddlers want to do things themselves, and channelling that into real self-care tasks works with the drive rather than against it.'),
  ('teeth-brushing-ritual-m19_21', 'This builds genuine independence at an age when wanting to be independent is at its peak.'),
  ('running-obstacle-course-m22_24', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('over-line-i-m22_24', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('walk-backward-m22_24', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('throw-catch-m22_24', 'At this age balance is still developing, and each attempt refines it a little further.'),
  ('pedal-tricycle-m22_24', 'Walking is new and still effortful, so this kind of practice is what turns a wobbly skill into an automatic one.'),
  ('gallop-forward-m22_24', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('step-alternating-stairs-m22_24', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('pull-heavy-objects-m22_24', 'Toddlers need to move a great deal, and this gives that energy somewhere useful to go while building balance and strength.'),
  ('drawing-horizontal-line-m22_24', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('copy-drawing-circle-m22_24', 'Fine motor skill at this stage is built through play rather than practice, and this offers plenty of both.'),
  ('snip-scissors-m22_24', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.'),
  ('from-jug-cup-m22_24', 'Small hands need a great deal of repetition, and this builds the strength and control that self-feeding and dressing will require.'),
  ('puzzle-i-m22_24', 'This is the age where hands become genuinely useful tools, and that happens through hundreds of small attempts.')
) as v(id, new_benefit)
where a.id = v.id;
